#############################################################################
# Makefile for building: qtdirs.app/Contents/MacOS/qtdirs
# Generated by qmake (2.01a) (Qt 4.8.7) on: Thu Jul 13 20:12:22 2017
# Project:  qtdirs.pro
# Template: app
# Command: /usr/local/bin/qmake -spec /usr/local/Cellar/qt@4/4.8.7_1/mkspecs/macx-g++ -o qtdirs.mk qtdirs.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -O2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/macx-g++ -I. -I/usr/local/Cellar/qt@4/4.8.7_1/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt@4/4.8.7_1/lib/QtCore.framework/Versions/4/Headers -I/usr/local/include -I. -F/usr/local/lib
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5
LIBS          = $(SUBLIBS) -F/usr/local/lib -L/usr/local/lib -framework QtCore -L/usr/local/opt/openssl/lib -L/usr/local/Cellar/qt@4/4.8.7_1/lib 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/local/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = qtdirs.cpp 
OBJECTS       = qtdirs.o
DIST          = /usr/local/Cellar/qt@4/4.8.7_1/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/common/g++-base.conf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/common/g++-macx.conf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/release.prf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/mac/x86_64.prf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/shared.prf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/lex.prf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/include_source_dir.prf \
		qtdirs.pro
QMAKE_TARGET  = qtdirs
DESTDIR       = 
TARGET        = qtdirs.app/Contents/MacOS/qtdirs

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: qtdirs.mk qtdirs.app/Contents/PkgInfo qtdirs.app/Contents/Resources/empty.lproj qtdirs.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) qtdirs.app/Contents/MacOS/ || $(MKDIR) qtdirs.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

qtdirs.mk: qtdirs.pro  /usr/local/Cellar/qt@4/4.8.7_1/mkspecs/macx-g++/qmake.conf /usr/local/Cellar/qt@4/4.8.7_1/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/common/g++-base.conf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/common/g++-macx.conf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/release.prf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/mac/x86_64.prf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/shared.prf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/lex.prf \
		/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/include_source_dir.prf \
		/usr/local/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec /usr/local/Cellar/qt@4/4.8.7_1/mkspecs/macx-g++ -o qtdirs.mk qtdirs.pro
/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/common/unix.conf:
/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/common/mac.conf:
/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/common/gcc-base-macx.conf:
/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/common/g++-base.conf:
/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/common/g++-macx.conf:
/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/qconfig.pri:
/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/release.prf:
/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/mac/x86_64.prf:
/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/shared.prf:
/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/qt.prf:
/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/moc.prf:
/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/resources.prf:
/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/uic.prf:
/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/lex.prf:
/usr/local/Cellar/qt@4/4.8.7_1/mkspecs/features/include_source_dir.prf:
/usr/local/lib/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Cellar/qt@4/4.8.7_1/mkspecs/macx-g++ -o qtdirs.mk qtdirs.pro

qtdirs.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) qtdirs.app/Contents || $(MKDIR) qtdirs.app/Contents 
	@$(DEL_FILE) qtdirs.app/Contents/PkgInfo
	@echo "APPL????" >qtdirs.app/Contents/PkgInfo
qtdirs.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) qtdirs.app/Contents/Resources || $(MKDIR) qtdirs.app/Contents/Resources 
	@touch qtdirs.app/Contents/Resources/empty.lproj
	
qtdirs.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) qtdirs.app/Contents || $(MKDIR) qtdirs.app/Contents 
	@$(DEL_FILE) qtdirs.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,qtdirs,g" -e "s,@TYPEINFO@,????,g" /usr/local/Cellar/qt@4/4.8.7_1/mkspecs/macx-g++/Info.plist.app >qtdirs.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/qtdirs1.0.0 || $(MKDIR) .tmp/qtdirs1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/qtdirs1.0.0/ && $(COPY_FILE) --parents qtdirs.cpp .tmp/qtdirs1.0.0/ && (cd `dirname .tmp/qtdirs1.0.0` && $(TAR) qtdirs1.0.0.tar qtdirs1.0.0 && $(COMPRESS) qtdirs1.0.0.tar) && $(MOVE) `dirname .tmp/qtdirs1.0.0`/qtdirs1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/qtdirs1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r qtdirs.app
	-$(DEL_FILE) qtdirs.mk


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

qtdirs.o: qtdirs.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtdirs.o qtdirs.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

